model:
  learning_rate: 0.0003
  target: celle_main.CELLE_trainer
  params:
    ckpt_path:
    condition_model_path: 
    condition_config_path: 
    vqgan_model_path: 
    vqgan_config_path: 
    image_key: threshold
    num_images: 2
    dim: 1280
    num_text_tokens: 33
    text_seq_len: 1000
    depth: 25
    heads: 16
    dim_head: 64
    attn_dropout: 0.1
    ff_dropout: 0.1
    attn_types: full
    rotary_emb: true
    fixed_embedding: True
    monitor: val/loss_epoch
    text_embedding: esm2
    loss_img_weight: 1
    loss_cond_weight: 1

data:
  target: celle_main.CellDataModule
  params:
    data_csv: 
    dataset: OpenCell
    sequence_mode: embedding
    vocab: esm2
    threshold: median
    text_seq_len: 1000
    crop_size: 256
    resize: 600
    batch_size: 1
    num_workers: 8